mise à jour 14:16

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -128,73 +128,77 @@ jobs:
 
       # Étape 6 - Démarrer le conteneur PostgreSQL
       - name: 6 - Démarrer le conteneur PostgreSQL
-        run: |
-          mkdir -p backend/logs || (echo "Erreur : Impossible de créer le répertoire des logs." && exit 1)
-          chmod -R 777 backend/logs
-          echo "=== Déploiement Backend : $(date) ===" > $LOG_FILE   
-
+        run: |          
           ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
-            set -e
-            echo '===================================' | tee -a $LOG_FILE
-            echo '[INFO - Étape 6] Configuration du conteneur PostgreSQL...' | tee -a $LOG_FILE
+          set -e
+          echo '===================================' | tee -a $LOG_FILE
+          echo '[INFO - Étape 6] Configuration du conteneur PostgreSQL...' | tee -a $LOG_FILE
 
-            # 6.1 - Sauvegarde conditionnelle de la base de données (production uniquement)
-            if [ "$ENV" = "prod" ]; then
-              echo '[INFO - Étape 6.1] Sauvegarde de la base de données en production...' | tee -a $LOG_FILE
-              BACKUP_FILE="/root/prod_backup_$(date +%Y%m%d%H%M%S).sql"
-              docker exec $POSTGRES_CONTAINER_NAME pg_dump -U $DB_USERNAME $DB_NAME > $BACKUP_FILE || {
+          # 6.1 - Vérification et création du répertoire de logs
+          echo '[INFO - Étape 6.1] Vérification et création du répertoire de logs...' | tee -a $LOG_FILE
+          mkdir -p backend/logs || { echo '[ERROR] Impossible de créer le répertoire des logs.' | tee -a $LOG_FILE; exit 1; }
+          chmod -R 777 backend/logs
+
+          # 6.2 - Sauvegarde conditionnelle de la base de données (production uniquement)
+          if [ \"$ENV\" = \"prod\" ]; then
+              echo '[INFO - Étape 6.2] Sauvegarde de la base de données en production...' | tee -a $LOG_FILE
+              BACKUP_FILE=\"/home/$SSH_USER/backups/prod_backup_\$(date +%Y%m%d%H%M%S).sql\"
+              docker exec $POSTGRES_CONTAINER_NAME pg_dump -U $DB_USERNAME $DB_NAME > \$BACKUP_FILE || {
                   echo '[ERROR] Échec de la sauvegarde de la base de données.' | tee -a $LOG_FILE
                   exit 1
               }
-              echo '[INFO] Sauvegarde effectuée : $BACKUP_FILE' | tee -a $LOG_FILE
+              echo '[INFO] Sauvegarde effectuée : \$BACKUP_FILE' | tee -a $LOG_FILE
 
-              # Créer un lien symbolique pour le dernier fichier de sauvegarde
-              echo '[INFO] Création d\'un lien symbolique vers le dernier fichier de sauvegarde...' | tee -a $LOG_FILE
-              ln -sf $BACKUP_FILE /home/$SSH_USER/backups/prod_backup_latest.sql || {
+              # 6.2.1 - Créer un lien symbolique pour le dernier fichier de sauvegarde
+              echo '[INFO - Étape 6.2.1] Création d\'un lien symbolique vers le dernier fichier de sauvegarde...' | tee -a $LOG_FILE
+              ln -sf \$BACKUP_FILE /home/$SSH_USER/backups/prod_backup_latest.sql || {
                   echo '[WARNING] Échec de la création du lien symbolique pour le fichier de sauvegarde.' | tee -a $LOG_FILE
               }
 
-              # 6.2 - Nettoyage des anciens backups
-              echo '[INFO - Étape 6.2] Nettoyage des anciens backups (plus de 7 jours)...' | tee -a $LOG_FILE
-              find /root -name 'prod_backup_*.sql' -type f -mtime +7 -exec rm -f {} \; || {
+              # 6.2.2 - Nettoyage des anciens backups
+              echo '[INFO - Étape 6.2.2] Nettoyage des anciens backups (plus de 7 jours)...' | tee -a $LOG_FILE
+              find /home/$SSH_USER/backups -name 'prod_backup_*.sql' -type f -mtime +7 -exec rm -f {} \; || {
                   echo '[WARNING] Échec du nettoyage des anciens backups.' | tee -a $LOG_FILE
               }
-              else
-                  echo '[INFO] Pas de sauvegarde nécessaire pour cet environnement.' | tee -a $LOG_FILE
-              fi
-             
+          else
+              echo '[INFO] Pas de sauvegarde nécessaire pour cet environnement.' | tee -a $LOG_FILE
+          fi
 
-            # 6.3 - Vérification et création du réseau Docker
-            if ! docker network ls --filter \"name=^$NETWORK\$\" --format '{{.Name}}' | grep -w $NETWORK; then
-              echo '[INFO - Étape 6.3] Création du réseau Docker : $NETWORK' | tee -a $LOG_FILE
+          # 6.3 - Vérification et création du réseau Docker
+          echo '[INFO - Étape 6.3] Vérification et création du réseau Docker...' | tee -a $LOG_FILE
+          if ! docker network ls --filter \"name=^$NETWORK\$\" --format '{{.Name}}' | grep -w $NETWORK; then
+              echo '[INFO] Création du réseau Docker : $NETWORK' | tee -a $LOG_FILE
               docker network create $NETWORK
-            else
+          else
               echo '[INFO] Réseau Docker déjà existant : $NETWORK' | tee -a $LOG_FILE
-            fi
+          fi
 
-            # 6.4 - Vérification et création du volume Docker
-            if ! docker volume ls --filter \"name=^$POSTGRES_VOLUME\$\" --format '{{.Name}}' | grep -w $POSTGRES_VOLUME; then
-              echo '[INFO - Étape 6.4] Création du volume Docker : $POSTGRES_VOLUME' | tee -a $LOG_FILE
+          # 6.4 - Vérification et création du volume Docker
+          echo '[INFO - Étape 6.4] Vérification et création du volume Docker...' | tee -a $LOG_FILE
+          if ! docker volume ls --filter \"name=^$POSTGRES_VOLUME\$\" --format '{{.Name}}' | grep -w $POSTGRES_VOLUME; then
+              echo '[INFO] Création du volume Docker : $POSTGRES_VOLUME' | tee -a $LOG_FILE
               docker volume create $POSTGRES_VOLUME
-            else
+          else
               echo '[INFO] Volume Docker déjà existant : $POSTGRES_VOLUME' | tee -a $LOG_FILE
-            fi
+          fi
 
-            # 6.5 - Arrêt et suppression de l’ancien conteneur PostgreSQL
-            if docker ps -a --filter \"name=$POSTGRES_CONTAINER_NAME\" --format '{{.Names}}' | grep -w $POSTGRES_CONTAINER_NAME; then
-              echo '[INFO - Étape 6.5] Suppression de l’ancien conteneur PostgreSQL : $POSTGRES_CONTAINER_NAME' | tee -a $LOG_FILE
+          # 6.5 - Arrêt et suppression de l’ancien conteneur PostgreSQL
+          echo '[INFO - Étape 6.5] Arrêt et suppression de l’ancien conteneur PostgreSQL...' | tee -a $LOG_FILE
+          if docker ps -a --filter \"name=$POSTGRES_CONTAINER_NAME\" --format '{{.Names}}' | grep -w $POSTGRES_CONTAINER_NAME; then
+              echo '[INFO] Suppression de l’ancien conteneur PostgreSQL : $POSTGRES_CONTAINER_NAME' | tee -a $LOG_FILE
               docker stop $POSTGRES_CONTAINER_NAME
               docker rm $POSTGRES_CONTAINER_NAME
-            else
+          else
               echo '[INFO] Aucun conteneur PostgreSQL existant à supprimer.' | tee -a $LOG_FILE
-            fi
+          fi
 
-            # 6.6 - Téléchargement de l’image PostgreSQL
-            echo '[INFO - Étape 6.6] Téléchargement de l’image PostgreSQL...' | tee -a $LOG_FILE
-            docker pull postgres:13
+          # 6.6 - Téléchargement de l’image PostgreSQL
+          echo '[INFO - Étape 6.6] Téléchargement de l’image PostgreSQL...' | tee -a $LOG_FILE
+          docker pull postgres:13
 
-            # 6.7 - Démarrage du nouveau conteneur PostgreSQL
-            docker run -d --name $POSTGRES_CONTAINER_NAME \
+          # 6.7 - Démarrage du nouveau conteneur PostgreSQL
+          echo '[INFO - Étape 6.7] Démarrage du nouveau conteneur PostgreSQL...' | tee -a $LOG_FILE
+          docker run -d --name $POSTGRES_CONTAINER_NAME \
               --network $NETWORK \
               -e POSTGRES_USER=$DB_USERNAME \
               -e POSTGRES_PASSWORD=$DB_PASSWORD \
@@ -203,17 +207,18 @@ jobs:
               -p $DB_PORT_EXT:$DB_PORT_INT \
               postgres:13
 
-            # 6.8 - Pause pour garantir le démarrage
-            echo '[INFO - Étape 6.8] Attente de 10 secondes pour PostgreSQL...' | tee -a $LOG_FILE
-            sleep 10
+          # 6.8 - Pause pour garantir le démarrage
+          echo '[INFO - Étape 6.8] Pause pour garantir le démarrage...' | tee -a $LOG_FILE
+          sleep 10
 
-            # 6.9 - Vérification finale de PostgreSQL
-            if docker exec $POSTGRES_CONTAINER_NAME pg_isready -U $DB_USERNAME; then
+          # 6.9 - Vérification finale de PostgreSQL
+          echo '[INFO - Étape 6.9] Vérification finale de PostgreSQL...' | tee -a $LOG_FILE
+          if docker exec $POSTGRES_CONTAINER_NAME pg_isready -U $DB_USERNAME; then
               echo '[SUCCESS - Étape 6] PostgreSQL est opérationnel.' | tee -a $LOG_FILE
-            else
+          else
               echo '[ERROR - Étape 6] PostgreSQL n’est pas prêt après le délai d’attente.' | tee -a $LOG_FILE
               exit 1
-            fi
+          fi
           " | tee -a $LOG_FILE
 
       # Étape 7 - Créer la base de données et l'utilisateur démo
