vérification de la base de donnée

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -217,6 +217,11 @@ jobs:
             fi
           done
 
+          if [ "$i" -eq 10 ]; then
+            echo "[ERROR] PostgreSQL n'a pas démarré après 10 tentatives." >&2
+            exit 1
+          fi
+
           # Étape 6.3.7.1 - Création de la base de données si elle n'existe pas
           echo '[INFO - Sous-étape 6.3.7.1] Vérification/création de la base de données...'
           docker exec "$POSTGRES_CONTAINER_NAME" psql -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
