ajustement

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -1,5 +1,4 @@
-# \backend\.github\workflows\deploy_backend.yml
-
+# Deploy Backend Workflow
 name: Deploy Backend
 
 on:
@@ -24,7 +23,7 @@ jobs:
           DOCKER_NAME: "back_node:latest"
         run: docker build -t $DOCKER_NAME -f Dockerfile.backend .
 
-      # Étape 3 : Push Docker image to registry (optionnel)
+      # Étape 3 - Push Docker image to registry (optionnel)
       - name: 3 - Push Docker image to registry
         env:
           DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
@@ -35,8 +34,6 @@ jobs:
             echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
             docker tag back_node:latest $DOCKER_REGISTRY/$DOCKER_USERNAME/back_node:latest
             docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/back_node:latest
-          else
-            echo "DOCKER_REGISTRY is not defined. Skipping Docker push."
           fi
 
       # Étape 4 - Start SSH agent and add key
@@ -89,10 +86,10 @@ jobs:
           CONTAINER_NAME: "${{ github.ref == 'refs/heads/master' && 'back_node_prod' || 'back_node_dev' }}"
           DB_USERNAME: ${{ secrets.DB_USERNAME }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-          DB_HOST: ${{ secrets.DB_HOST }}
+          DB_HOST: ${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}
           DB_PORT_EXT: "${{ github.ref == 'refs/heads/master' && 5434 || 5433 }}"
           DB_NAME: "${{ github.ref == 'refs/heads/master' && 'postgres_prod' || 'postgres_dev' }}"
-          DATABASE_URL: "postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${DB_PORT_EXT}/${DB_NAME}"
+          DATABASE_URL: "postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${DB_HOST}:${DB_PORT_EXT}/${DB_NAME}"
           NETWORK: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'prod_network' || 'dev_network' }}
           PORT: ${{ secrets.PORT }}
           JWT_SECRET: ${{ secrets.JWT_SECRET }}
@@ -112,9 +109,15 @@ jobs:
               back_node:latest
           "
 
-
-      # Étape 7 - Set Remote Git URL (si nécessaire)
+      # Étape 7 - Set Remote Git URL
       - name: 7 - Set Remote Git URL
         env:
           GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
         run: git remote set-url origin $GIT_REPO_URL
+
+      # Étape 8 - Health Check
+      - name: 8 - Health Check
+        run: |
+          ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
+            docker exec ${{ github.ref == 'refs/heads/master' && 'back_node_prod' || 'back_node_dev' }} curl http://localhost:7000/api/health || echo 'Health check failed'
+          "
