20:09

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -243,10 +243,8 @@ jobs:
           echo "Nom utilisateur : $DB_USERNAME"
           echo "Mot de passe de la base : $DB_PASSWORD"
 
-          # 7.1 - Sauvegarde conditionnelle de la base de données
-          echo "[INFO - 7.1] Sauvegarde conditionnelle de la base de données..."
-
-          # Déterminer le répertoire et le fichier de sauvegarde en fonction de l'environnement
+           # 7.1.1 - Déterminer le répertoire et le fichier de sauvegarde en fonction de l'environnement
+          echo "[INFO - 7.1.1] Détermination du répertoire de sauvegarde..."
           if [ "$ENV" == "prod" ]; then
               BACKUP_DIR="/home/$SSH_USER/backups/prod"
               BACKUP_FILE="$BACKUP_DIR/prod_backup_$(date +%Y%m%d%H%M%S).sql"
@@ -255,32 +253,32 @@ jobs:
               BACKUP_FILE="$BACKUP_DIR/dev_backup_$(date +%Y%m%d%H%M%S).sql"
           fi
 
-          # 7.1.0 - Créer le répertoire de sauvegarde s'il n'existe pas
-          echo "[INFO 7.1.0] Création du répertoire de sauvegarde : $BACKUP_DIR..."
+          # 7.1.2 - Créer le répertoire de sauvegarde s'il n'existe pas
+          echo "[INFO - 7.1.2] Création du répertoire de sauvegarde : $BACKUP_DIR..."
           ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
               mkdir -p $BACKUP_DIR
           "
 
-          # 7.1.1 - Effectuer la sauvegarde si la base de données existe
-          echo "[INFO 7.1.1] Sauvegarde de la base de données : $DB_NAME..."
+          # 7.1.3 - Effectuer la sauvegarde si la base de données existe
+          echo "[INFO - 7.1.3] Sauvegarde de la base de données : $DB_NAME..."
           if docker exec $POSTGRES_CONTAINER_NAME pg_isready -U $DB_USERNAME; then
               docker exec $POSTGRES_CONTAINER_NAME pg_dump -U $DB_USERNAME $DB_NAME > $BACKUP_FILE || {
-                  echo "[ERROR] Échec de la sauvegarde de la base de données."
+                  echo "[ERROR - 7.1.3] Échec de la sauvegarde de la base de données."
                   exit 1
               }
-              echo "[INFO 7.1.2] Sauvegarde effectuée avec succès : $BACKUP_FILE"
+              echo "[INFO - 7.1.4] Sauvegarde effectuée avec succès : $BACKUP_FILE"
           else
-              echo "[WARNING] La base de données '$DB_NAME' n'est pas accessible, sauvegarde impossible."
+              echo "[WARNING - 7.1.3] La base de données '$DB_NAME' n'est pas accessible, sauvegarde impossible."
           fi
 
-          # 7.1.3 - Nettoyage des anciennes sauvegardes (plus de 7 jours)
-          echo "[INFO 7.1.3] Nettoyage des sauvegardes anciennes (plus de 7 jours)..."
+          # 7.1.5 - Nettoyage des anciennes sauvegardes (plus de 7 jours)
+          echo "[INFO - 7.1.5] Nettoyage des sauvegardes anciennes (plus de 7 jours)..."
           ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
               find $BACKUP_DIR -name '*.sql' -type f -mtime +7 -exec rm -f {} \;
-          " || echo "[WARNING] Échec du nettoyage des anciennes sauvegardes."
+          " || echo "[WARNING - 7.1.5] Échec du nettoyage des anciennes sauvegardes."
 
-          # 7.2.0 - Création de la base de données et des rôles
-          echo "[INFO - 7.2.0] Création de la base de données et des rôles..."
+          # 7.2 - Création de la base de données et des rôles
+          echo "[INFO - 7.2] Création de la base de données et des rôles..."
 
           ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
               set -e
@@ -290,23 +288,19 @@ jobs:
               sleep 20
 
               # 7.2.2 - Vérifier si le rôle postgres existe et le créer si nécessaire
-              echo \"[INFO 7.2.2] Vérification et création du rôle 'postgres' si nécessaire...\"
+              echo '[INFO - 7.2.2] Vérification et création du rôle postgres si nécessaire...'
               docker exec -i $POSTGRES_CONTAINER_NAME psql -U $DB_USERNAME -tc \"SELECT 1 FROM pg_roles WHERE rolname='postgres'\" | grep -q 1 || {
-                  echo '[INFO 7.2.3] Création du rôle postgres...'
+                  echo '[INFO - 7.2.3] Création du rôle postgres...'
                   docker exec -i $POSTGRES_CONTAINER_NAME psql -U $DB_USERNAME -c \"CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD '$DB_PASSWORD';\"
               }
 
-              # 7.2.4 - Pause pour laisser le temps à PostgreSQL de stabiliser le rôle
-              echo \"[INFO 7.2.4] Pause de 20 secondes pour garantir la stabilité...\"
-              sleep 20
+              # 7.2.4 - Nettoyer l'ancienne base de données et les rôles associés
+              echo '[INFO - 7.2.4] Nettoyage des anciennes bases et rôles...'
+              docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -c \"DROP DATABASE IF EXISTS $DB_NAME;\" || echo '[WARNING - 7.2.4] Impossible de supprimer la base de données.'
+              docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -c \"DROP ROLE IF EXISTS $DB_USERNAME;\" || echo '[WARNING - 7.2.4] Impossible de supprimer le rôle.'
 
-              # 7.2.5 - Nettoyer l'ancienne base de données et les rôles associés
-              echo \"[INFO 7.2.5] Nettoyage des anciennes bases et rôles...\"
-              docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -c \"DROP DATABASE IF EXISTS $DB_NAME;\" || echo '[WARNING] Impossible de supprimer la base de données.'
-              docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -c \"DROP ROLE IF EXISTS $DB_USERNAME;\" || echo '[WARNING] Impossible de supprimer le rôle.'
-
-              # 7.2.6 - Préparer le script SQL pour la base de données
-              echo \"[INFO 7.2.6] Préparation du script SQL pour la création/mise à jour de la base...\"
+              # 7.2.5 - Préparer le script SQL pour la base de données
+              echo '[INFO - 7.2.5] Préparation du script SQL pour la création/mise à jour de la base...'
           
           cat <<EOF > init_database.sql
           -- Terminer les connexions actives si la base existe
@@ -325,40 +319,40 @@ jobs:
             GRANT ALL PRIVILEGES ON DATABASE \"${DB_NAME}\" TO \"${DB_USERNAME}\";
           EOF
             
-            # 7.2.7 - Pause avant l'exécution des commandes SQL
-            echo \"[INFO 7.2.7] Pause de 20 secondes avant exécution des commandes SQL...\"
+            # 7.2.6 - Pause avant l'exécution des commandes SQL
+            echo '[INFO - 7.2.6] Pause de 20 secondes avant exécution des commandes SQL...'
             sleep 20
 
-            # 7.2.8 - Exécuter le script SQL
-            echo \"[INFO 7.2.8] Exécution des commandes SQL...\"
+            # 7.2.7 - Exécuter le script SQL
+            echo '[INFO - 7.2.7] Exécution des commandes SQL...'
             docker cp init_database.sql $POSTGRES_CONTAINER_NAME:/tmp/init_database.sql
             docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -f /tmp/init_database.sql
 
-            # 7.2.9 - Nettoyage
-            echo \"[INFO 7.2.9] Nettoyage des fichiers temporaires...\"
+            # 7.2.8 - Nettoyage
+            echo '[INFO - 7.2.8] Nettoyage des fichiers temporaires...'
             rm init_database.sql
             docker exec $POSTGRES_CONTAINER_NAME rm /tmp/init_database.sql
           "
-            # 7.3.0 - Restauration de la base de données à partir du backup si en prod
-            if [ "$ENV" == "prod" ]; then
-                echo "[INFO - 7.3.0] Restauration de la base de données à partir du backup..."
 
+            # 7.3 - Restauration de la base de données en production
+            if [ "$ENV" == "prod" ]; then
+                echo "[INFO - 7.3] Restauration de la base de données à partir du backup..."
                 RESTORE_FILE="/home/$SSH_USER/backups/prod/prod_backup_latest.sql"
                 if [ -f "$RESTORE_FILE" ]; then
-                    echo "[INFO] Fichier de backup trouvé : $RESTORE_FILE"
+                    echo "[INFO - 7.3.1] Fichier de backup trouvé : $RESTORE_FILE"
                     docker cp $RESTORE_FILE $POSTGRES_CONTAINER_NAME:/tmp/restore.sql
                     docker exec -i $POSTGRES_CONTAINER_NAME psql -U postgres -d $DB_NAME < /tmp/restore.sql || {
-                        echo "[ERROR] Échec de la restauration à partir du fichier $RESTORE_FILE."
+                        echo "[ERROR - 7.3.1] Échec de la restauration à partir du fichier $RESTORE_FILE."
                         exit 1
                     }
-                    echo "[INFO 7.3.1] Restauration effectuée avec succès."
+                    echo "[INFO - 7.3.2] Restauration effectuée avec succès."
                 else
-                    echo "[WARNING] Aucun fichier de backup trouvé pour la restauration."
+                    echo "[WARNING - 7.3.1] Aucun fichier de backup trouvé pour la restauration."
                 fi
             fi
 
-            # 7.3.2 - Pause pour garantir la stabilisation avant validation finale
-            echo "[INFO 7.3.2] Pause de 20 secondes avant validation finale..."
+            # 7.3.3 - Pause pour garantir la stabilisation avant validation finale
+            echo "[INFO 7.3.3] Pause de 20 secondes avant validation finale..."
             sleep 20
 
             # 7.4 - Validation finale
