vérification des variable étape 8

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -211,19 +211,21 @@ jobs:
       - name: 8 - Déployer le conteneur Backend
         run: |
           ssh -p $SSH_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa $SSH_USER@$SERVER_IP "
+          
           # 8.1 - Début du déploiement
           echo '[INFO - Étape 8.1] Début du déploiement du backend...' | tee -a $LOG_FILE
 
-          # 8.2 - Validation des variables d'environnement
-          echo '[INFO - Étape 8.2] Validation des variables d'environnement :' | tee -a $LOG_FILE
-          echo \"DATABASE_URL=***$DB_HOST:$DB_PORT_INT/$DB_NAME\" | tee -a $LOG_FILE
-          echo \"NODE_ENV=$ENV\" | tee -a $LOG_FILE
-          echo \"JWT_SECRET=********\" | tee -a $LOG_FILE
-          echo \"NETWORK=$NETWORK\" | tee -a $LOG_FILE
-          echo \"CONTAINER_NAME=$CONTAINER_NAME\" | tee -a $LOG_FILE
-          echo \"DOCKER_NAME=$DOCKER_NAME\" | tee -a $LOG_FILE
-          echo \"MOUNT_PATH=$MOUNT_PATH\" | tee -a $LOG_FILE
-          echo \"BACKEND_PORT=$BACKEND_PORT\" | tee -a $LOG_FILE
+          # 8.2 - Vérification des variables d'environnement
+          echo '[INFO - Étape 8.2] Vérification des variables d'environnement...' | tee -a $LOG_FILE
+
+          MANDATORY_VARS=(DB_USERNAME DB_PASSWORD DB_NAME DB_HOST DB_PORT_INT DB_PORT_EXT JWT_SECRET NODE_ENV BACKEND_PORT NETWORK MOUNT_PATH)
+          for VAR in \"${MANDATORY_VARS[@]}\"; do
+            if [ -z \"\${!VAR}\" ]; then
+              echo \"[ERROR] La variable $VAR est manquante ou vide.\" | tee -a $LOG_FILE
+              exit 1
+            fi
+            echo \"[INFO] $VAR=\${!VAR}\" | tee -a $LOG_FILE
+          done
 
           # Étape 8.3 - Vérification et gestion stricte du fichier .env
           echo '[INFO - Étape 8.3] Vérification et gestion du fichier .env...' | tee -a $LOG_FILE
@@ -244,7 +246,7 @@ jobs:
           DB_PORT_INT=$DB_PORT_INT
           DB_PORT_EXT=$DB_PORT_EXT
           JWT_SECRET=$JWT_SECRET
-          NODE_ENV=$ENV
+          NODE_ENV=$NODE_ENV
           SERVER_PORT=$BACKEND_PORT
           EOF
 
