ajustement étape 8

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -209,17 +209,6 @@ jobs:
           BACKEND_PORT=$BACKEND_PORT
           EOF
 
-          # Vérification et création du dossier /app si inexistant
-          docker exec $CONTAINER_NAME mkdir -p /app || echo '[INFO] Dossier /app déjà existant.' | tee -a $LOG_FILE
-
-          # Copier le fichier .env dans le conteneur
-          if docker cp /tmp/.env $CONTAINER_NAME:/app/.env; then
-            echo '[INFO] Fichier .env copié avec succès.' | tee -a $LOG_FILE
-          else
-            echo '[ERROR] Échec définitif de la copie du fichier .env.' | tee -a $LOG_FILE
-            exit 1
-          fi
-
           # Arrêter et supprimer l'ancien conteneur si nécessaire
           if docker ps -a --filter \"name=$CONTAINER_NAME\" --format '{{.Names}}' | grep -w $CONTAINER_NAME; then
             echo '[INFO] Arrêt et suppression de l’ancien conteneur : $CONTAINER_NAME' | tee -a $LOG_FILE
@@ -238,13 +227,22 @@ jobs:
             -p $BACKEND_PORT:$BACKEND_PORT \
             $DOCKER_NAME || { echo '[ERROR] Échec du démarrage du conteneur backend.' | tee -a $LOG_FILE; exit 1; }
 
-          # Vérification de l'état du conteneur
-          echo '[INFO] Vérification état du conteneur backend...' | tee -a $LOG_FILE
-          docker ps --filter \"name=$CONTAINER_NAME\" | tee -a $LOG_FILE
-
           # Pause pour permettre au conteneur de démarrer
           echo '[INFO] Attente de 10 secondes pour le démarrage du backend...' | tee -a $LOG_FILE
           sleep 10
+
+          # Copier le fichier .env dans le conteneur
+          echo '[INFO] Copie du fichier .env dans le conteneur...' | tee -a $LOG_FILE
+          if docker cp /tmp/.env $CONTAINER_NAME:/app/.env; then
+            echo '[INFO] Fichier .env copié avec succès.' | tee -a $LOG_FILE
+          else
+            echo '[ERROR] Échec définitif de la copie du fichier .env.' | tee -a $LOG_FILE
+            exit 1
+          fi
+
+          # Vérification de l'état du conteneur
+          echo '[INFO] Vérification état du conteneur backend...' | tee -a $LOG_FILE
+          docker ps --filter \"name=$CONTAINER_NAME\" | tee -a $LOG_FILE
 
           # Test de santé sur /health
           echo '[INFO] Test endpoint /health...' | tee -a $LOG_FILE
