ajout contrôle variables pour .env

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -274,6 +274,17 @@ jobs:
       
           ssh -p "$SSH_PORT" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /tmp/git_id_rsa "$SSH_USER@$SERVER_IP" << EOF
             set -e
+
+            # Sous-étape 8.0 : Vérification des variables chargées
+            echo "[INFO - Sous-étape 8.0] Vérification des variables chargées..."
+            MANDATORY_VARS=(ENV DATABASE_URL JWT_SECRET BACKEND_PORT)
+            for VAR in "${MANDATORY_VARS[@]}"; do
+              if [ -z "\${!VAR}" ]; then
+                echo "[ERROR] La variable \$VAR est manquante ou vide." >&2
+                exit 1
+              fi
+              echo "[INFO] \$VAR=\${!VAR}"
+            done
       
             # Étape 8.1 - Création d’un fichier temporaire pour les variables
             echo '[INFO - Étape 8.1] Création d’un fichier temporaire avec les variables...'
