ajustement server.js

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -347,6 +347,15 @@ jobs:
               docker logs "$CONTAINER_NAME"
               exit 1
             }
+            
+            # 📦 Installation de wget et net-tools
+            echo "[INFO - 8.3.3.1.1] Installation de wget et net-tools..."
+            docker exec "$CONTAINER_NAME" apt-get update && \
+            docker exec "$CONTAINER_NAME" apt-get install -y wget net-tools || {
+              echo "[ERROR] L'installation de wget/net-tools a échoué." >&2
+              docker logs "$CONTAINER_NAME"
+              exit 1
+            }
 
             # 🚀 Lancement de l'application manuellement
             echo "[INFO - 8.3.3.2] Démarrage manuel du serveur backend..."
