15:47

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -200,14 +200,14 @@ jobs:
             echo '[INFO - 6.8] Démarrage du nouveau conteneur PostgreSQL...' | tee -a $LOG_FILE
 
             echo "[INFO] Affichage des variables générées : " | tee -a $LOG_FILE
-          MANDATORY_VARS=(ENV DB_NAME DB_USERNAME DB_PASSWORD DB_HOST DATABASE_URL MOUNT_PATH CONTAINER_NAME DB_PORT_INT DB_PORT_EXT BACKEND_PORT NETWORK JWT_SECRET POSTGRES_CONTAINER_NAME POSTGRES_VOLUME)
-          for VAR in "${MANDATORY_VARS[@]}"; do
-            if [ -z "${!VAR}" ]; then
-              echo "[ERROR] La variable $VAR est manquante ou vide." | tee -a $LOG_FILE
-              exit 1
-            fi
-            echo "[INFO] $VAR=${!VAR}" | tee -a $LOG_FILE
-          done
+            MANDATORY_VARS=(ENV DB_NAME DB_USERNAME DB_PASSWORD DB_HOST DATABASE_URL MOUNT_PATH CONTAINER_NAME DB_PORT_INT DB_PORT_EXT BACKEND_PORT NETWORK JWT_SECRET POSTGRES_CONTAINER_NAME POSTGRES_VOLUME)
+            for VAR in "${MANDATORY_VARS[@]}"; do
+              if [ -z "${!VAR}" ]; then
+                echo "[ERROR] La variable $VAR est manquante ou vide." | tee -a $LOG_FILE
+                exit 1
+              fi
+              echo "[INFO] $VAR=${!VAR}" | tee -a $LOG_FILE
+            done
 
             # Vérifier si le volume existe
             if docker volume ls --filter "name=^${POSTGRES_VOLUME}$" --format '{{.Name}}' | grep -wq "${POSTGRES_VOLUME}"; then
