ajouter la ligne mount .env dans le container

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -344,17 +344,18 @@ jobs:
                 docker rm "$CONTAINER_NAME" || echo '[WARNING] Échec de la suppression du conteneur.'
               fi
         
-              # Étape 8.6 - Lancement du nouveau conteneur backend
-              echo '[INFO - Étape 8.6] Lancement du conteneur backend...'
-              docker run -d --name "$CONTAINER_NAME" \
-                --network "$NETWORK" \
-                -v "$MOUNT_PATH:/app" \
-                -w /app \
-                -p "$BACKEND_PORT:$BACKEND_PORT" \
-                "$DOCKER_NAME" || {
-                  echo '[ERROR] Échec du démarrage du conteneur backend.' >&2
-                  exit 1
-                }
+            # Étape 8.6 - Lancement du nouveau conteneur backend
+            echo '[INFO - Étape 8.6] Lancement du conteneur backend...'
+            docker run -d --name "$CONTAINER_NAME" \
+              --network "$NETWORK" \
+              -v "$MOUNT_PATH:/app" \
+              -w /app \
+              --env-file "$MOUNT_PATH/.env" \
+              -p "$BACKEND_PORT:$BACKEND_PORT" \
+              "$DOCKER_NAME" || {
+                echo '[ERROR] Échec du démarrage du conteneur backend.' >&2
+                exit 1
+              }
       
             # Étape 8.7 - Vérification du conteneur
             echo '[INFO - Étape 8.7] Vérification que le conteneur est actif...'
