amélioration de la gestion des migrations et backup

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -368,9 +368,16 @@ jobs:
             # Étape 8.8 - Gestion des migrations avec backup et rollback
             echo '[INFO - Étape 8.8] Vérification et application des migrations Prisma...'
 
-            # Étape 8.8.1 - Définir le répertoire de backup
-            BACKUP_DIR="/backup_bd"
-            mkdir -p "$BACKUP_DIR"
+            # Étape 8.8.1 - Définir le répertoire de backup en fonction de l'environnement
+            BASE_DIR=$(dirname "$MOUNT_PATH")  # Prend le répertoire parent de $MOUNT_PATH
+            BACKUP_DIR="$BASE_DIR/backup_bd"   # Ajoute le dossier de sauvegarde dédié
+
+            # Création du répertoire si nécessaire
+            echo "[INFO - Étape 8.8.1] Création du répertoire de backup : $BACKUP_DIR"
+            mkdir -p "$BACKUP_DIR" || {
+              echo "[ERROR] Échec de la création du répertoire de backup : $BACKUP_DIR" >&2
+              exit 1
+            }
 
             # Étape 8.8.2 - Backup de la base de données avant les migrations
             echo '[INFO - Étape 8.8.2] Création d’un backup de la base de données avant migration...'
