ajustement prisma

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -348,13 +348,15 @@ jobs:
             echo '[INFO - Étape 8.6] Lancement du conteneur backend...'
 
             docker run -d --name "$CONTAINER_NAME" \
-            --network "$NETWORK" \
-            -w /app \
-            --env-file "$MOUNT_PATH/.env" \
-            -p "$BACKEND_PORT:$BACKEND_PORT" \
-            "$DOCKER_NAME" || {
-              echo '[ERROR] Échec du démarrage du conteneur backend.' >&2
-              exit 1
+              --network "$NETWORK" \
+              -v "$MOUNT_PATH/.env:/app/.env" \
+              -v "$MOUNT_PATH/logs:/app/logs" \
+              -w /app \
+              --env-file "$MOUNT_PATH/.env" \
+              -p "$BACKEND_PORT:$BACKEND_PORT" \
+              "$DOCKER_NAME" || {
+                echo '[ERROR] Échec du démarrage du conteneur backend.' >&2
+                exit 1
             }
 
             # Vérification du contenu de /app/prisma
