16:26

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -197,44 +197,22 @@ jobs:
             docker pull postgres:13
 
             # 6.8 - Démarrage du nouveau conteneur PostgreSQL
-            echo '[INFO - 6.8] Affichage des variables utilisées pour le démarrage du conteneur...'
-            echo "POSTGRES_CONTAINER_NAME: $POSTGRES_CONTAINER_NAME"
-            echo "NETWORK: $NETWORK"
-            echo "DB_USERNAME: $DB_USERNAME"
-            echo "DB_PASSWORD: $DB_PASSWORD"
-            echo "DB_NAME: $DB_NAME"
-            echo "POSTGRES_VOLUME: $POSTGRES_VOLUME"
-            echo "DB_PORT_EXT: $DB_PORT_EXT"
-            echo "DB_PORT_INT: $DB_PORT_INT"
             echo '[INFO - 6.8] Démarrage du nouveau conteneur PostgreSQL...' | tee -a $LOG_FILE
 
-            # Vérifier si le volume existe
-            if docker volume ls --filter "name=^${POSTGRES_VOLUME}$" --format '{{.Name}}' | grep -wq "${POSTGRES_VOLUME}"; then
-              echo "[INFO - 6.8.1] Volume ${POSTGRES_VOLUME} déjà existant. Lancement du conteneur sans recréer le volume..." | tee -a $LOG_FILE
-              docker run -d --name $POSTGRES_CONTAINER_NAME \
-                --network $NETWORK \
-                -e POSTGRES_USER=$DB_USERNAME \
-                -e POSTGRES_PASSWORD=$DB_PASSWORD \
-                -e POSTGRES_DB=$DB_NAME \
-                -p $DB_PORT_EXT:$DB_PORT_INT \
-                postgres:13 || {
-                echo '[ERROR - 6.8.2] Échec du lancement du conteneur PostgreSQL sans recréer le volume.' | tee -a $LOG_FILE
-                exit 1
-              }
-            else
-              echo "[INFO - 6.8.2] Volume ${POSTGRES_VOLUME} inexistant. Lancement du conteneur avec création du volume..." | tee -a $LOG_FILE
-              docker run -d --name $POSTGRES_CONTAINER_NAME \
-                --network $NETWORK \
-                -e POSTGRES_USER=$DB_USERNAME \
-                -e POSTGRES_PASSWORD=$DB_PASSWORD \
-                -e POSTGRES_DB=$DB_NAME \
-                -v ${POSTGRES_VOLUME}:/var/lib/postgresql/data \
-                -p $DB_PORT_EXT:$DB_PORT_INT \
-                postgres:13 || {
-                echo '[ERROR - 6.8.3] Échec du lancement du conteneur PostgreSQL avec création du volume.' | tee -a $LOG_FILE
-                exit 1
-              }
-            fi
+            # Exécutez docker run directement avec le volume spécifié
+            docker run -d --name $POSTGRES_CONTAINER_NAME \
+              --network $NETWORK \
+              -e POSTGRES_USER=$DB_USERNAME \
+              -e POSTGRES_PASSWORD=$DB_PASSWORD \
+              -e POSTGRES_DB=$DB_NAME \
+              -v ${POSTGRES_VOLUME}:/var/lib/postgresql/data \
+              -p $DB_PORT_EXT:$DB_PORT_INT \
+              postgres:13 || {
+              echo '[ERROR - 6.8] Échec du lancement du conteneur PostgreSQL.' | tee -a $LOG_FILE
+              exit 1
+            }
+
+            echo '[SUCCESS - 6.8] Conteneur PostgreSQL démarré avec succès.' | tee -a $LOG_FILE
 
             # 6.9 - Vérification de PostgreSQL
             echo '[INFO - 6.9] Vérification de PostgreSQL jusqu’à ce qu’il soit prêt...' | tee -a $LOG_FILE
@@ -247,21 +225,26 @@ jobs:
             echo "POSTGRES_VOLUME: $POSTGRES_VOLUME"
             echo "DB_PORT_EXT: $DB_PORT_EXT"
             echo "DB_PORT_INT: $DB_PORT_INT"
+
             MAX_ATTEMPTS=30
-            for i in \$(seq 1 \$MAX_ATTEMPTS); do
+            for i in $(seq 1 $MAX_ATTEMPTS); do
               if docker exec $POSTGRES_CONTAINER_NAME pg_isready -U $DB_USERNAME; then
-                echo \"PostgreSQL est prêt après \$i seconde(s).\" | tee -a $LOG_FILE
+                echo "PostgreSQL est prêt après $i seconde(s)." | tee -a $LOG_FILE
                 break
               fi
-              echo \"PostgreSQL n’est pas encore prêt, tentative \$i/\$MAX_ATTEMPTS...\" | tee -a $LOG_FILE
+              echo "PostgreSQL n’est pas encore prêt, tentative $i/$MAX_ATTEMPTS..." | tee -a $LOG_FILE
               sleep 1
-              if [ \"\$i\" -eq \"\$MAX_ATTEMPTS\" ]; then
-                echo \"[ERROR - 6.9] PostgreSQL n’est pas prêt après \$MAX_ATTEMPTS secondes.\" | tee -a $LOG_FILE
+              if [ "$i" -eq "$MAX_ATTEMPTS" ]; then
+                echo "[ERROR - 6.9] PostgreSQL n’est pas prêt après $MAX_ATTEMPTS secondes." | tee -a $LOG_FILE
                 exit 1
               fi
             done
 
-            # Ajout des vérifications pour le contenu du conteneur
+            # Pause avant les vérifications
+            echo '[INFO - 6.9.1] Attente de 60 secondes avant la vérification du contenu du conteneur...' | tee -a $LOG_FILE
+            sleep 60
+
+            # Vérifications du contenu du conteneur
             echo "[INFO - 6.9.1] Vérification du contenu du conteneur PostgreSQL..." | tee -a $LOG_FILE
             if docker exec $POSTGRES_CONTAINER_NAME psql -U $DB_USERNAME -c "\l"; then
               echo "[INFO - 6.9.2] Liste des bases de données affichée avec succès." | tee -a $LOG_FILE
@@ -273,11 +256,9 @@ jobs:
             else
               echo "[WARNING - 6.9.3] Impossible d'afficher la liste des rôles." | tee -a $LOG_FILE
             fi
-            
-            echo '[SUCCESS - Étape 6] PostgreSQL est opérationnel.' | tee -a $LOG_FILE            
-          " | tee -a $LOG_FILE        
 
-      
+            echo '[SUCCESS - Étape 6] PostgreSQL est opérationnel.' | tee -a $LOG_FILE            
+          " | tee -a $LOG_FILE
 
       - name: 8 - Déployer le conteneur Backend
         run: |
